### ISSUE TITLE
Glitchy screen upon loading controls

### ISSUE THREAD

**Issue by emmaloool** [15466-Slinky/FinalProject#21]
https://pasteboard.co/WfvHe3f0DX8V.png

**Comment by emmaloool** [comment]
Also a "WARNING: GL OUT OF MEMORY"

**Comment by gdr22** [comment]
> https://pasteboard.co/WfvHe3f0DX8V.png

Did you do anything specific to make this occur?

**Comment by wenxuanou** [comment]
> Also a "WARNING: GL OUT OF MEMORY"

Could you post your hardware status as well?

**Comment by emmaloool** [comment]
<img width="609" alt="Screen Shot 2021-11-30 at 11 07 57 AM" src="https://user-images.githubusercontent.com/33307632/144083832-ea2a470d-ca3f-49e9-b823-b8f717e97032.png">

I'm running on Big Sur 11.6

**Comment by annehe9** [comment]
Resolved
