### ISSUE TITLE
I can't grab one particular ledge in level 1

### ISSUE THREAD

**Issue by gcwhitfield** [15466-Slinky/FinalProject#22]
MacOS 10.14.6
Processor: 2.8 GHz Intel Core i7
Memory: 16 GB 2133 MHz LPDDR3
GPU: Intel HD Graphics 630 1536 MB

Steps to reproduce: 
1) Go to the top of level one
2) Try to grab the ledge that leads to the final area of level one

https://user-images.githubusercontent.com/29950517/144081204-4dfb57f2-c27d-4c84-b5d6-f708ff4c9035.mov

It seems like this ledge is grab-able if the player catapults themselves upwards from one of the lower ledges. However, if I try to grab the ledge by jumping form the side (as shown in the video) then I cannot grab it

**Comment by annehe9** [comment]
Thanks for your feedback, we intended for this to be part of the level design, but we may make this more clear.
