### ISSUE TITLE
I get stuck on a ledge when I catapult myself into it

### ISSUE THREAD

**Issue by gcwhitfield** [15466-Slinky/FinalProject#23]
MacOS 10.14.6
Processor: 2.8 GHz Intel Core i7
Memory: 16 GB 2133 MHz LPDDR3
GPU: Intel HD Graphics 630 1536 MB

Steps to reproduce:
1) In level 3, go to this ledge (shown in the video) and catapult yourself into it
2) The cat will get stuck on the ledge WITHOUT be pressing the "ledge grab" button (spacebar)

https://user-images.githubusercontent.com/29950517/144082595-8c888d7b-820c-4f12-98c2-3e0636bc04c8.mov

**Comment by annehe9** [comment]
This is the intended behavior, you automatically grab ledges, and hold space to extend. We will make this more clear in the instructions.
